services:
  dock-discovry-service:
    build: ./discovry-service
    container_name: dock-discovry-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval:  10s
      retries:  4
  dock-config-service:
    build: ./config-service
    container_name: dock-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
    depends_on:
      dock-discovry-service:
        condition:  service_healthy
  dock-client-service:
    build: ./client
    container_name: dock-client-service
    ports:
      - '2020:2020'
    expose:
      - '2020'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:2020/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-config-service:
        condition: service_healthy
  dock-produit-service:
    build: ./produit
    container_name: dock-produit-service
    ports:
      - '2021:2021'
    expose:
      - '2021'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:2021/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-client-service:
        condition: service_healthy
  dock-vente-service:
    build: ./vente
    container_name: dock-vente-service
    ports:
      - '2022:2022'
    expose:
      - '2022'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:2022/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-produit-service:
        condition:  service_healthy
  dock-gateway-service:
    build: ./gatewya-service
    container_name: dock-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-vente-service:
        condition:
          service_healthy